// <auto-generated />
using System;
using BandAPI.Controllers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BandAPI.Migrations
{
    [DbContext(typeof(BandAlbumContext))]
    partial class BandAlbumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

            modelBuilder.Entity("BandAPI.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6543677d-0262-4f6d-a06e-45a4fb9ac9b0"),
                            BandId = new Guid("3c0b8198-c7c5-4521-bdd1-cff61b98a05f"),
                            Description = "One of the best heavy metal albums ever",
                            Title = "Master of puppets"
                        },
                        new
                        {
                            Id = new Guid("9554622a-57cc-4a2d-a648-988e47a1fad4"),
                            BandId = new Guid("0ecca8db-3116-40e3-8178-7a45efa5edf7"),
                            Description = "Amaznig Rock album with Raw sound",
                            Title = "Appetite for Destruction"
                        },
                        new
                        {
                            Id = new Guid("fb89faa5-ffab-43f7-b8a6-19fa0a8ba213"),
                            BandId = new Guid("aece25e6-3785-4840-a7d7-3dd18f209dab"),
                            Description = "Amaznig Rock album with Raw sound",
                            Title = "Huxy and griill"
                        },
                        new
                        {
                            Id = new Guid("4ebfdc70-4d79-4c43-96a4-d0eda3cd6939"),
                            BandId = new Guid("7d5577a5-abf1-430d-8591-58a50b58af80"),
                            Description = "Amaznig Rock album with Raw sound",
                            Title = "Huxy and griill"
                        },
                        new
                        {
                            Id = new Guid("341b0995-b0cf-437f-9ba6-de15d0c430a4"),
                            BandId = new Guid("b5262e7b-4ffe-4a62-a2f5-7c4f090eeb40"),
                            Description = "Jaleel is a good boy Rock album with Raw sound",
                            Title = "Jaleel and grill"
                        });
                });

            modelBuilder.Entity("BandAPI.Entities.Band", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Founded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MainGenre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Bands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c0b8198-c7c5-4521-bdd1-cff61b98a05f"),
                            Founded = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Heavy Metal",
                            Name = "Metallica"
                        },
                        new
                        {
                            Id = new Guid("0ecca8db-3116-40e3-8178-7a45efa5edf7"),
                            Founded = new DateTime(1985, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Heavy Metal",
                            Name = "Guns n Roses"
                        },
                        new
                        {
                            Id = new Guid("aece25e6-3785-4840-a7d7-3dd18f209dab"),
                            Founded = new DateTime(1980, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Heavy Metal",
                            Name = "Metallica"
                        },
                        new
                        {
                            Id = new Guid("7d5577a5-abf1-430d-8591-58a50b58af80"),
                            Founded = new DateTime(1980, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Alternative",
                            Name = "Metallica"
                        },
                        new
                        {
                            Id = new Guid("b5262e7b-4ffe-4a62-a2f5-7c4f090eeb40"),
                            Founded = new DateTime(1980, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Pop",
                            Name = "A - ha "
                        });
                });

            modelBuilder.Entity("BandAPI.Entities.Album", b =>
                {
                    b.HasOne("BandAPI.Entities.Band", "Band")
                        .WithMany("Albums")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");
                });

            modelBuilder.Entity("BandAPI.Entities.Band", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
